Models/Director.cs
using FirstProject.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace FirstProject.Models
{
    public class Director : BaseEntity
    {
        public int Age { get; set; }
        public DateTime DOB { get; set; }
        public string? City { get; set; }
        public bool Gender { get; set; }
        public string? Category { get; set; }
        public string? Language { get; set; }

        //Relatioships
        public ICollection<Director_Actor>? Directors_Actors { get; set; }
        public ICollection<Movie_Director>? Movies_Directors { get; set; }

    }
}

Controllers/DirectorsController.cs
using FirstProject.Data.Services;
using FirstProject.Hubs;
using FirstProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace FirstProject.Controllers
{
    public class DirectorsController : Controller
    {
        private readonly IDirectorsService _service;
        private readonly IHubContext<NotificationHub> _hubContext;


        public DirectorsController(IDirectorsService service, IHubContext<NotificationHub> hubContext)
        {
            _service = service;
            _hubContext = hubContext;
        }

        public async Task<IActionResult> Index(string search)
        {

            var data = await _service.GetAllAsync();
            if (search != null)
            {
                var result = (from s in data
                              where s.Name.ToLower().Contains(search.ToLower())
                              select s).ToList();
                return View(result);
            }
            return View(data);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Director director)
        {
            if (!ModelState.IsValid)
            {
                return View(director);
            }

            await _service.AddAsync(director);
            await _hubContext.Clients.All.SendAsync("ReceiveMessage", "New director has been added, please referesh the page");
            return RedirectToAction(nameof(Index));
        }

        //Get :Directors/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var directorDetails = await _service.GetByIdAsync(id);
            if (directorDetails == null) return View("NotFound");
            return View(directorDetails);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var moviesDetails = await _service.GetByIdAsync(id);
            if (moviesDetails == null) return View("NotFound");
            return View(moviesDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Director director)
        {
            if (!ModelState.IsValid)
            {
                return View(director);
            }

            await _service.UpdateAsync(id, director);
            await _hubContext.Clients.All.SendAsync("ReceiveMessage", "Director has been updated, please referesh the page");
            return RedirectToAction(nameof(Index));
        }
        //Get:Actors/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var directorDetails = await _service.GetByIdAsync(id);
            if (directorDetails == null) return View("NotFound");
            return View(directorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var directorDetails = await _service.GetByIdAsync(id);
            if (directorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            await _hubContext.Clients.All.SendAsync("ReceiveMessage", "Director has been deleted, please referesh the page");
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Directors/Create.cshtml
@model Director

@{
    ViewData["Title"] = "Add a new Director";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
        <h1>Add a New Director</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form>

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Age" class="control-label"></label>
                        <input asp-for="Age" class="form-control" />
                        <span asp-validation-for="Age" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DOB" class="control-label"></label>
                        <input asp-for="DOB" class="form-control" />
                        <span asp-validation-for="DOB" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                        @Html.CheckBoxFor(m => m.Gender)
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="City" class="control-label"></label>
                        <input asp-for="City" class="form-control" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Category" class="control-label"></label>
                        <input asp-for="Category" class="form-control" />
                        <span asp-validation-for="Category" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Language" class="control-label"></label>
                        <input asp-for="Language" class="form-control" />
                        <span asp-validation-for="Language" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right"
                            id="btnSubmit" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $('#btnSubmit').click(function (event) {
                event.preventDefault();
                var directorData = {
                    Name: $('#Name').val(),
                    Age: $('#Age').val(),
                    DOB: $('#DOB').val(),
                    Gender: $('#Gender').val(),
                    City: $('#City').val(),
                    Category: $("#Category").val(),
                    Language: $('#Language').val()
                };

                if (directorData.Name == "" || directorData.Age == "" || directorData.DOB == "" || directorData.Gender == "" || directorData.City == "" || directorData.Category == "" || directorData.Language == "") {
                    alert("Please fill all the fields");
                    return false;
                }
                else if(directorData.Name <=3 )
                {
                    alert("Name should be greater than 3 characters");
                    return false;
                }
                else if(directorData.Age <=0)
                {
                    alert("Age should be greater than 0");
                    return false;
                }
                else if(directorData.City <=3)
                {
                    alert("City should be greater than 3 characters");
                    return false;
                }
                else if(directorData.Language <=3)
                {
                    alert("Language should be greater than 3 characters");
                    return false;
                }

                $.ajax({
                    type: "POST",
                    url: "/Directors/Create",
                    data: directorData,
                    dataType: "html",
                    contentType: 'application/x-www-form-urlencoded',
                    success: function (data) {
                        window.location.href = "/Directors/Index";
                        alert('Director Added Successfully');
                    },
                    error: function (error) {
                        alert("Error occured!!", error)
                    }
                });
            });
        });
    });   
</script>

Views/Directors/Delete.cshtml
@model Director

@{
    ViewData["Title"] = "Delete director";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
        <h1>Delete confirmation @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" readonly />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Age" class="control-label"></label>
                    <input asp-for="Age" class="form-control" readonly />
                    <span asp-validation-for="Age" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DOB" class="control-label"></label>
                    <input asp-for="DOB" class="form-control" readonly />
                    <span asp-validation-for="DOB" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" readonly />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Gender" class="control-label"></label>
                    @if (Model.Gender)
                    {
                        <input  class="form-control" readonly value="Male" />
                    }
                    else
                    {
                        <input  class="form-control" readonly value="Female" />
                    }
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Category" class="control-label"></label>
                    <input asp-for="Category" class="form-control" readonly />
                    <span asp-validation-for="Category" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Language" class="control-label"></label>
                    <input asp-for="Language" class="form-control" readonly />
                    <span asp-validation-for="Language" class="text-danger"></span>
                </div>

                <div class="form-group" >
                    <form>
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Confirm" class="btn btn-danger float-right" id="btnSubmit" />
                    </form>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $('#btnSubmit').click(function (event) {
                event.preventDefault();
                var directorData = {
                    Id: @Model.Id,
                };
                $.ajax({
                    type: "POST",
                    url: "/Directors/Delete",
                    data: directorData,
                    dataType: "html",
                    contentType: 'application/x-www-form-urlencoded',
                    success: function (data) {
                        window.location.href = "/Directors/Index";
                        alert('Director Deleted Successfully');
                    },
                    error: function (error) {
                        alert("Error occured!!", error)
                    }
                });
            });
        });
    }); 
</script>

Views/Directors/Details.cshtml
@model Director

@{
    ViewData["Title"] = "Detials of the Director";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Details of @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" readonly/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Age" class="control-label"></label>
                        <input asp-for="Age" class="form-control" readonly/>
                        <span asp-validation-for="Age" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DOB" class="control-label"></label>
                        <input asp-for="DOB" class="form-control" readonly/>
                        <span asp-validation-for="DOB" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="City" class="control-label"></label>
                        <input asp-for="City" class="form-control" readonly/>
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                         @if (Model.Gender)
                    {
                        <input  class="form-control" readonly value="Male" />
                    }
                    else
                    {
                        <input  class="form-control" readonly value="Female" />
                    }
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Category" class="control-label"></label>
                        <input asp-for="Category" class="form-control" readonly/>
                        <span asp-validation-for="Category" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Language" class="control-label"></label>
                        <input asp-for="Language" class="form-control" readonly/>
                        <span asp-validation-for="Language" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <a class="btn btn-outline-success float-right" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
            </div>
        </div>
    </div>
</div>

Views/Directors/Edit.cshtml
@model Director

@{
    ViewData["Title"] = "Update a new director";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update a New Director</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" id="Name"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Age" class="control-label"></label>
                        <input asp-for="Age" class="form-control" id="Age"/>
                        <span asp-validation-for="Age" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DOB" class="control-label"></label>
                        <input asp-for="DOB" class="form-control" id="DOB"/>
                        <span asp-validation-for="DOB" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="City" class="control-label"></label>
                        <input asp-for="City" class="form-control" id="City"/>
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                        @Html.CheckBoxFor(m => m.Gender, new { id="Gender"})
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Category" class="control-label"></label>
                        <input asp-for="Category" class="form-control" id="Category"/>
                        <span asp-validation-for="Category" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Language" class="control-label"></label>
                        <input asp-for="Language" class="form-control" id="Language"/>
                        <span asp-validation-for="Language" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" id="btnSubmit" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {  
        $(function() {  
            $('#btnSubmit').click(function(event) {  
                event.preventDefault();  
                var directorData = {  
                    Id : @Model.Id,
                    Name: $('#Name').val(),
                    Age: $('#Age').val(),
                    DOB: $('#DOB').val(),
                    City: $('#City').val(),
                    Gender :  document.getElementById("Gender").checked,
                    Category : $('#Category').val(),
                    Language : $('#Language').val(),
                    CreatedDate : `@Model.CreatedDate`
                };  
                if (directorData.Name == "" || directorData.Age == "" || directorData.DOB == "" || directorData.Gender == "" || directorData.City == "" || directorData.Category == "" || directorData.Language == "") {
                    alert("Please fill all the fields");
                    return false;
                }
                else if(directorData.Name <=3 )
                {
                    alert("Name should be greater than 3 characters");
                    return false;
                }
                else if(directorData.Age <=0)
                {
                    alert("Age should be greater than 0");
                    return false;
                }
                else if(directorData.City <=3)
                {
                    alert("City should be greater than 3 characters");
                    return false;
                }
                else if(directorData.Language <=3)
                {
                    alert("Language should be greater than 3 characters");
                    return false;
                }

                $.ajax({  
                    type: "POST",  
                    url: "/Directors/Edit",  
                    data: directorData,  
                    dataType: "html",  
                    contentType: 'application/x-www-form-urlencoded',  
                    success: function(data) {  
                        window.location.href = "/Directors/Index";
                        alert('Director Updated Successfully'); 
                    },  
                    error: function(error) {  
                        alert("Error occured!!",error)  
                    }
                });  
            });  
        });  
    }); 
</script>

Views/Directors/Index.cshtml
@model IEnumerable<Director>

@{
    ViewData["Title"] = "List of Director";
}
@using (Html.BeginForm("Index", "Directors", FormMethod.Get))

{
    @Html.TextBox("search")
    <input type="submit" name="submit" value="Search" />

}
@if (Model.Count() == 0)
{
    <div class="row text-center">
        <div class="col-md-6 offset-3">
            <h1 class="text-info">No Record Found</h1>
            <hr />
        </div>
    </div>
}
else
{
    <div class="row" style="width:100%;">
        <div style="width:100%">
            <table class="table">
                <thead>
                    <tr class="text-center">
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th>@Html.DisplayNameFor(model => model.Age)</th>
                        <th>@Html.DisplayNameFor(model => model.Category)</th>
                        <th>@Html.DisplayNameFor(model => model.DOB)</th>
                        <th>@Html.DisplayNameFor(model => model.City)</th>
                        <th>@Html.DisplayNameFor(model => model.Gender)</th>
                        <th>@Html.DisplayNameFor(model => model.Category)</th>
                        <th>@Html.DisplayNameFor(model => model.Language)</th>
                        <th>Options</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr style="background-color:#fff;">
                            <td style="text-align:center">@item.Name</td>
                            <td style="text-align:center">@item.Age</td>
                            <td style="text-align:center">@item.Category</td>
                            <td style="text-align:center">@item.DOB</td>
                            <td style="text-align:center">@item.City</td>
                            @if(@item.Gender == true)
                            {
                            <td style="text-align:center">Male</td>
                            }
                            else{
                            <td style="text-align:center">Female</td>

                            }
                            <td style="text-align:center">@item.Category</td>
                            <td style="text-align:center">@item.Language</td>
                            <td class="align-middle" style="text-align:center">
                                <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                                <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                                <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}
<div style="position:fixed;right:25px; bottom:25px" class="text-white">
    <a asp-controller="Directors" asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle"></i>Add New</a>
</div>