Models/Actor.cs
using System.ComponentModel.DataAnnotations;
using FirstProject.Data.Base;

namespace FirstProject.Models
{
    public class Actor : BaseEntity
    {
        [Required (ErrorMessage = "Age is required")]
        public int Age { get; set; }
        [Required]
        public DateTime DOB { get; set; }
        [Required]
        public string? City { get; set; }
        [Required]
        public bool Gender { get; set; }
        [Required]
        public string? Hobbie { get; set; }

        //Relatioships
        public ICollection<Actor_Movie>? Actors_Movies { get; set; }
        public ICollection<Director_Actor>? Directors_Actors { get; set; }

    }
}

Controllers/ActorsController.cs
using FirstProject.Data.Services;
using FirstProject.Hubs;
using FirstProject.Models;
using MassTransit;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace FirstProject.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;
        private readonly IHubContext<NotificationHub> _hubContext;
        public ActorsController(IActorsService service, IHubContext<NotificationHub> hubContext)
        {
            _service = service;
            _hubContext = hubContext;
        }

        public async Task<IActionResult> Index(string search)
        {

            var data = await _service.GetAllAsync();
            if (search != null)
            {
                var result = (from s in data
                              where s.Name.ToLower().Contains(search.ToLower())
                              select s).ToList();
                return View(result);
            }
            return View(data);
        }

        //Get request : Actors/Create
        public IActionResult Create()
        {
            var data = _service.GetAllAsync();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }

            await _service.AddAsync(actor);
            await _hubContext.Clients.All.SendAsync("ReceiveMessage", actor.Name, "has been added, please referesh the page");
            return RedirectToAction(nameof(Index));
        }

        //Get :Actors/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            var movieDetails = await _service.ActorsMoviesViewModelAsync(id);
            ViewBag.Movies = movieDetails.Movies;
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.UpdateAsync(id, actor);
            await _hubContext.Clients.All.SendAsync("ReceiveMessage", actor.Name, "has been updated, please referesh the page");
            return RedirectToAction(nameof(Index));
        }
        //Get:Actors/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            await _hubContext.Clients.All.SendAsync("ReceiveMessage", actorDetails.Name, "has been deleted, please referesh the page");
            return RedirectToAction(nameof(Index));
        }

    }
}

Views/Actors/Create.cshtml
@model Actor

@{
    ViewData["Title"] = "Add a new actor";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
        <h1>Add a New Actor</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" id="Name" />
                </div>

                <div class="form-group">
                    <label asp-for="Age" class="control-label"></label>
                    <input asp-for="Age" class="form-control" id="Age" />
                </div>

                <div class="form-group">
                    <label asp-for="DOB" class="control-label"></label>
                    <input asp-for="DOB" class="form-control" id="DOB" />
                </div>

                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" id="City" />
                </div>

                <div class="form-group">
                    <label asp-for="Gender" class="control-label"></label>
                    <input type="checkbox" id="Gender" />
                </div>

                <input asp-for="Hobbie" class="form-control" readonly id="Hobbie" hidden/>

                @foreach (var error in "Action,Adventure,Comedy,Drama,Horror,Sci-Fi,Thriller".Split(','))
                {
                    <div>
                        <input type="checkbox" value="@error" class="btn btn-outline-success float-right" itemid="@error"
                        onclick="hello(value);" />
                        @error
                    </div>
                }
                <div class="form-group">
                    @* <input type="submit" value="Create" class="btn btn-outline-success float-right" /> *@
                    <input type="submit" value="Create" class="btn btn-outline-success float-right" id="btnSubmit" />
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var hobbies = [];
    function hello(Value) {
        if (hobbies.includes(Value)) {
            hobbies.splice(hobbies.indexOf(Value), 1);
        }
        else {
            hobbies.push(Value);
        }
        let hobbies_string = hobbies.join(",");
        console.log(hobbies, hobbies_string);
        document.getElementById("Hobbie").value = hobbies_string.toString();
    }


    $(document).ready(function () {
        $(function () {
            $('#btnSubmit').click(function (event) {
                event.preventDefault();
                var Name = $("#Name").val();
                var Age = $("#Age").val();
                var DOB = $("#DOB").val();
                var City = $("#City").val();
                var Gender = $("#Gender").val();
                var Hobbie = $("#Hobbie").val();

                if (Name == "" || Age == "" || DOB == "" || City == "" || Gender == "" || Hobbie == "") {
                    alert("Please fill all the fields");
                    return false;
                }
                else if (Name.length <= 3) {
                    alert("Name should be greater than 3 characters");
                    return false;
                }
                else if (Age <= 25) {
                    alert("Age should be greater than 25");
                    return false;
                }
                else if (Age >= 75) {
                    alert("Age should be less than 75");
                    return false;
                }
                else if (City.length <= 3) {
                    alert("City should be greater than 3 characters");
                    return false;
                }

                var actorData = {
                    Name: $('#Name').val(),
                    Age: $('#Age').val(),
                    DOB: $('#DOB').val(),
                    City: $('#City').val(),
                    Gender: document.getElementById("Gender").checked,
                    Hobbie: $('#Hobbie').val()
                };
                $.ajax({
                    type: "POST",
                    url: "/Actors/Create",
                    data: actorData,
                    dataType: "html",
                    contentType: 'application/x-www-form-urlencoded',
                    success: function (data) {
                        window.location.href = "/Actors/Index";
                        alert('Actor Added Successfully');
                    },
                    error: function (error) {
                        alert("Error occured!!", error)
                    }
                });
            });
        });
    });
</script>

Views/Actors/Delete.cshtml
@model Actor

@{
    ViewData["Title"] = "Delete actor";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
        <h1>Delete confirmation @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" readonly />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Age" class="control-label"></label>
                    <input asp-for="Age" class="form-control" readonly />
                    <span asp-validation-for="Age" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DOB" class="control-label"></label>
                    <input asp-for="DOB" class="form-control" readonly />
                    <span asp-validation-for="DOB" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" readonly />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Gender" class="control-label"></label>
                    @if (Model.Gender)
                    {
                        <input class="form-control" readonly value="Male" />
                    }
                    else
                    {
                        <input class="form-control" readonly value="Female" />
                    }
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <form>
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Confirm" class="btn btn-danger float-right" id="btnSubmit" />
                    </form>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $('#btnSubmit').click(function (event) {
                event.preventDefault();
                var actorData = {
                    Id: @Model.Id,
                };
                $.ajax({
                    type: "POST",
                    url: "/Actors/Delete",
                    data: actorData,
                    dataType: "html",
                    contentType: 'application/x-www-form-urlencoded',
                    success: function (data) {
                        window.location.href = "/Actors/Index";
                        alert('Actor Deleted Successfully');
                    },
                    error: function (error) {
                        alert("Error occured!!", error)
                    }
                });
            });
        });
    }); 
</script>

Views/Actors/Details.cshtml
@model Actor

@{
    ViewData["Title"] = "Detials of the actor";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
        <h1>Details for @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" readonly />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Age" class="control-label"></label>
                    <input asp-for="Age" class="form-control" readonly />
                    <span asp-validation-for="Age" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DOB" class="control-label"></label>
                    <input asp-for="DOB" class="form-control" readonly />
                    <span asp-validation-for="DOB" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" readonly />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Gender" class="control-label"></label>
                    @if (Model.Gender)
                    {
                        <input class="form-control" readonly value="Male" />
                    }
                    else
                    {
                        <input class="form-control" readonly value="Female" />
                    }
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Hobbie" class="control-label"></label>
                    <input asp-for="Hobbie" class="form-control" readonly />
                    <span asp-validation-for="Hobbie" class="text-danger"></span>
                </div>
                    <h5>Movies</h5>
                @if (@ViewBag.Movies.Count >0)
                {
                    @foreach (var item in @ViewBag.Movies)
                    {
                        <div class="form-group">@item.Name</div>
                    }
                }
                else{
                    <div class="form-group">No movies</div>
                }

                <div class="form-group">
                    <a class="btn btn-outline-success float-right" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Actors/Edit.cshtml
@model Actor

@{
    ViewData["Title"] = "Update a new actor";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
        <h1>Update a New Actor</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form>

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Age" class="control-label"></label>
                        <input asp-for="Age" class="form-control" />
                        <span asp-validation-for="Age" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DOB" class="control-label"></label>
                        <input asp-for="DOB" class="form-control" />
                        <span asp-validation-for="DOB" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="City" class="control-label"></label>
                        <input asp-for="City" class="form-control" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                        @Html.CheckBoxFor(m => m.Gender,new { id="Gender"})
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Hobbie" class="control-label"></label>
                        <input asp-for="Hobbie" class="form-control" id="Hobbie" readonly hidden/>
                        <span asp-validation-for="Hobbie" class="text-danger"></span>
                    </div>
                    @foreach (var item in "Action,Adventure,Comedy,Drama,Horror,Sci-Fi,Thriller".Split(','))
                    {
                        @if ((Model.Hobbie).Contains(@item))
                        {
                            <div>
                            <input type="checkbox" name="@item" value="@item" checked onclick="hobbies(value);"/>
                            <text>@item</text>
                            </div>
                        }
                        else
                        {
                            <div>
                            <input type="checkbox" name="@item" value="@item" onclick="hobbies(value);" />
                            <text>@item</text>
                            </div>
                        }
                    }
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" id="btnSubmit" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
var Hobbie = [];
    (() => {
        var d = document.getElementById("Hobbie").value;
        Hobbie = d.split(',');
        console.log(Hobbie,'Hobbie');
    })()

    function hobbies(Value) {
        if(Hobbie.includes(Value.trim())){
            console.log(Hobbie.length,'length')
            Hobbie.splice(Hobbie.indexOf(Value), 1);
        }
        else{
            console.log(Hobbie.length,'length')
            Hobbie.push(Value.trim());
        }
        let hobbies_string = Hobbie.join(",");
        console.log(Hobbie, hobbies_string,'array');
        document.getElementById("Hobbie").value = hobbies_string.toString();
    }
    $(document).ready(function() {  
        $(function() {  
            $('#btnSubmit').click(function(event) {  
                event.preventDefault(); 
                var Name = $("#Name").val();
                var Age = $("#Age").val();
                var DOB = $("#DOB").val();
                var City = $("#City").val();
                var Gender = $("#Gender").val();
                var Hobbie = $("#Hobbie").val();

                if (Name == "" || Age == "" || DOB == "" || City == "" || Gender == "" || Hobbie == "") {
                    alert("Please fill all the fields");
                    return false;
                }
                else if (Name.length <= 3) {
                    alert("Name should be greater than 3 characters");
                    return false;
                }
                else if (Age <= 25) {
                    alert("Age should be greater than 25");
                    return false;
                }
                else if (Age >= 75) {
                    alert("Age should be less than 75");
                    return false;
                }
                else if (City.length <= 3) {
                    alert("City should be greater than 3 characters");
                    return false;
                } 
                var actorData = {  
                    Id : @Model.Id,
                    Name: $('#Name').val(),
                    Age: $('#Age').val(),
                    DOB: $('#DOB').val(),
                    City: $('#City').val(),
                    Gender: document.getElementById("Gender").checked,
                    Hobbie : $('#Hobbie').val(),
                    CreatedDate : `@Model.CreatedDate`,
                };  
                $.ajax({  
                    type: "POST",  
                    url: "/Actors/Edit",  
                    data: actorData,  
                    dataType: "html",  
                    contentType: 'application/x-www-form-urlencoded',  
                    success: function(data) {  
                        window.location.href = "/Actors/Index";
                        alert('Actor Updated Successfully'); 
                    },  
                    error: function(error) {  
                        alert("Error occured!!",error)  
                    }
                });  
            });  
        });  
    }); 
</script>

Views/Actors/Index.cshtml
@model IEnumerable<Actor>

@{
    ViewData["Title"] = "List of Actors";
}
@using (Html.BeginForm("Index", "Actors", FormMethod.Get))

{
    @Html.TextBox("search")
    <input type="submit" name="submit" value="Search" />
}
@if (Model.Count() == 0)
{
    <div class="row text-center">
        <div class="col-md-6 offset-3">
            <h1 class="text-info">No Record Found</h1>
            <hr />
        </div>
    </div>
}
else
{
    <div class="row">
        <div style="width:100%">
            <table class="table">
                <thead>
                    <tr class="text-center">
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th>@Html.DisplayNameFor(model => model.Age)</th>
                        <th>@Html.DisplayNameFor(model => model.DOB)</th>
                        <th>@Html.DisplayNameFor(model => model.City)</th>
                        <th>@Html.DisplayNameFor(model => model.Gender)</th>
                        <th>@Html.DisplayNameFor(model => model.Hobbie)</th>
                        <th>Options</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="bg-light">
                            <td style="text-align:center">@item.Name</td>
                            <td style="text-align:center">@item.Age</td>
                            <td style="text-align:center">@item.DOB</td>
                            <td style="text-align:center">@item.City</td>
                            @if(@item.Gender == true)
                            {
                            <td style="text-align:center">Male</td>
                            }
                            else{
                            <td style="text-align:center">Female</td>

                            }
                            <td style="text-align:center">@item.Hobbie</td>
                            <td class="align-middle" style="text-align:center">
                                <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id">
                                    <i class="bi bi-pencil-square"></i>Edit
                                </a> |
                                <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye"></i>Details
                                </a> |
                                <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id">
                                    <i class="bi bi-trash"></i>Delete
                                </a>
                            </td>
                        </tr>

                    }
                </tbody>
            </table>
        </div>
    </div>

}
<div style="position:fixed;right:25px; bottom:25px" class="text-white">
    <a asp-controller="Actors" asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle"></i>Add New</a>
</div>
<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/notification.js"></script>